
defaults:
  - mappings/parameters
  
dataset: dwd

weather:
  parameter: tas  # standardized variable name (e.g., tas, pr, rsds)

location:
  lat: 52.5070
  lon: 14.1372
  buffer_km: 25

time_range:
  start_date: "1950-01-01"
  end_date: "2024-12-31"

output:
  filename: "weather_data.csv"