
defaults:
  - _self_
  - mappings/parameters
  
dataset: dwd

weather:
  parameter: tas  # standardized variable name (e.g., tas, pr, rsds)

location:
  lat: 52.5070
  lon: 14.1372
  buffer_km: 25

time_range:
  start_date: "2000-01-01"
  end_date: "2024-12-31"

output:
  out_dir: "./data/"
  filename: "{provider}_{parameter}_LAT{lat}_LON{lon}_{start}_{end}.csv"